name: Inventory Sync

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps chromium
    
    - name: Run inventory sync
      env:
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        SHOPIFY_SHOP_URL: ${{ secrets.SHOPIFY_SHOP_URL }}
        OASE_USERNAME: ${{ secrets.OASE_USERNAME }}
        OASE_PASSWORD: ${{ secrets.OASE_PASSWORD }}
      run: python3 main.py --supplier oase_outdoors
